version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    user: "1000"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start:dev
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - ${NODE_PORT}:${NODE_PORT}
