name: Continuous Integration Checks

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Run lint check
        run: pnpm lint:check

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Run format check
        run: pnpm format:check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Run unit tests
        run: pnpm test:unit:coverage
